### ISSUE TITLE
freetype dependence fixes

### ISSUE THREAD

**Issue by HinTak** [tomlechner/laxkit#1]
I think the missing FT_done_face error you saw is due to 2nd of the below.
```
diff --git a/lax/lax-config b/lax/lax-config
index f9cf77f..73da540 100755
--- a/lax/lax-config
+++ b/lax/lax-config
@@ -5,7 +5,7 @@ $LaxkitVersion="0.0.8.1";
 $prefix="/home/tom/p/sourceforge/laxkit/lax";
 $iprefix="/interfaces";
 
-$imlibflags=`imlib2-config --libs`;
+$imlibflags=`imlib2-config --libs` `freetype-config --libs`;
 $ldsoflags  ="-L/usr/X11R6/lib -lX11 -lm -lXpm -lpng -lcups $imlibflags -llaxinterfaces -llaxkit\n";
 $ldflags="-L/usr/X11R6/lib -lX11 -lm -lXpm -lpng -lcups $imlibflags $prefix$iprefix/liblaxinterfaces.a $prefix/liblaxkit.a\n";
 $cppflags = "";
diff --git a/laxinput/Makefile b/laxinput/Makefile
index e2b66d8..8ac77af 100644
--- a/laxinput/Makefile
+++ b/laxinput/Makefile
@@ -15,7 +15,7 @@ LAXIDIR=$(LAXDIR)/interfaces
 LAXOBJDIR=$(LAXDIR)
 
 LD=g++
-LDFLAGS= -L/usr/X11R6/lib -lX11 -lm -lcairo   `imlib2-config --libs` -lfontconfig -lXext -lXi -lXft -lssl -L$(LAXDIR) -L$(LAXIDIR)
+LDFLAGS= -L/usr/X11R6/lib -lX11 -lm -lcairo   `imlib2-config --libs` `freetype-config --libs` -lsqlite3 -lfontconfig -lXext -lXi -lXft -lssl -L$(LAXDIR) -L$(LAXIDIR)
 DEBUGFLAGS= -g -Wall
 CPPFLAGS= $(DEBUGFLAGS) -I. -I.. -I$(LAXDIR)/.. -I../include -I../src -I/usr/include/freetype2
 
```

**Comment by HinTak** [comment]
I needed to add the freetype-config as well as the sqlite3 to get it to build in fedora.

**Comment by HinTak** [comment]
There is also a lot of stray extra tab at the end of each Makefile . emacs complains about that and asked me to confirm each time.

**Comment by HinTak** [comment]
The recommended way of adding freetype to the compiler command line is either via freetype-config or pkg-config. e.g.

$ pkg-config freetype2 --libs
-lfreetype 

$ freetype-config --libs
-lfreetype

Both your configure and your Makefile's are very non-standard and unusual :-(.

**Comment by HinTak** [comment]
Yes,  undo'ing all my customization and redo'ing, only the latter part is needed:

```
--- a/laxinput/Makefile
+++ b/laxinput/Makefile
@@ -15,7 +15,7 @@ LAXIDIR=$(LAXDIR)/interfaces
 LAXOBJDIR=$(LAXDIR)
 
 LD=g++
-LDFLAGS= -L/usr/X11R6/lib -lX11 -lm -lcairo   `imlib2-config --libs` -lfontconfig -lXext -lXi -lXft -lssl -L$(LAXDIR) -L$(LAXIDIR)
+LDFLAGS= -L/usr/X11R6/lib -lX11 -lm -lcairo   `imlib2-config --libs` `freetype-config --libs` -lsqlite3 -lfontconfig -lXext -lXi -lXft -lssl -L$(LAXDIR) -L$(LAXIDIR)
 DEBUGFLAGS= -g -Wall
 CPPFLAGS= $(DEBUGFLAGS) -I. -I.. -I$(LAXDIR)/.. -I../include -I../src -I/usr/include/freetype2
 
```

**Comment by HinTak** [comment]
I think it would also be better if you put
 ' "make depends" is also needed if compiled from git'

before "make" , where "Simply do:" is, in addition of instead of it in the separate "build from git" section.

**Comment by HinTak** [comment]
There is "pkg-config freetype2 --cflags" and "freetype-config --cflags" also, instead of those hard-coded "-I/usr/include/freetype2", etc.

**Comment by tomlechner** [comment]
I think partially fixed.. I replaced all the hardcoded freetype references in the Makefiles.
If there's similar problems in other libraries, I should probably use pkg-config --cflags/--libs more.

My strategy for Makefiles and configure, if you can call it a strategy, is to do the bare minimum to make it work. Maybe not the most forward looking strategy, but still not as many headaches and extra files as autotools! 

The freetype issue I saw before was due to an older version of harfbuzz used in Ubuntu 14.04. The missing function was added a few months after 14.04 came out!

**Comment by HinTak** [comment]
Yes, I think this is fixed.

I'll also suggest cleaning up your CPPFLAGS - "-I. -I.. -I../.. -I$(LAXDIR)/.." is a bit messy and probably not needed, and hard-coding '-g -gdwarf-2' is also a bit unsighty... and the console message flood also - do people need to or want to read those? :-)

**Comment by tomlechner** [comment]
By the way, I just removed various -I. and -I..
Modifying $(LAXDIR)/.. I'll save for another day, as it requires changing scattered documentation as well as the makefiles.

The console message flood makes it easier for me to debug improper reference counting and various other things difficult to track in a debugger. "make hidegarbage" makes it go away before doing the usual make.

**Comment by HinTak** [comment]
The hidegarbage thing is probably better solved by doing something like what I do with difference in run time environments for FontVal. (mono have some extra things which MS dotnet does not have). "make USE_MONO_SECURITY=true" adds -DHAVE_MONO_X509 to the compiler flags, which in turn enables sections which are "#ifdef HAVE_MONO_X509" in the code.

The relevant part of the Makefile is this (it is not C but mono  C# compiler) - "make BUILD=.net2" means targetting the older windows runtime, which is definitely not mono:

```
ifeq "$(BUILD)" ".net2"
EXTRA_DEV_OPTS=/nostdlib /platform:AnyCPU /reference:/usr/lib/mono/2.0/System.dll \
-define:MS_TESTING -lib:../00_refs/ -r:truetype \
/reference:/usr/lib/mono/2.0/mscorlib.dll \
-lib:/usr/lib/mono/2.0
else
ifeq "$(USE_MONO_SECURITY)" "true"
EXTRA_DEV_OPTS=-define:HAVE_MONO_X509 -r:Mono.Security
else
EXTRA_DEV_OPTS=
endif
endif
```

**Comment by tomlechner** [comment]
Early on I hoped for a compile flag to easily flip off console debug messages, but I never could get it to work. Plus it's a lot easier to whip out one line sending something to cerr, then to also encase it in ifdefs, making it 3 lines each, instead of just one. Each "garbage" line I start with DBG, so it's very easy to isolate every bit of extra stuff like that. If there were a lot of devs working on Laidout, I would probably be more diligent about removing that stuff once I don't need it before committing.

**Comment by HinTak** [comment]
Another thing you can try is what ghostscript does: all debug messages uses a set of routines, which have two versions, one that does nothing and another set that print to stderr, and which one to use depends on which make target you run. You could go that way, by just replacing all your std::cerr on off, by say, myerr, which has two versions controlled by a ifdef. Then you just have one ifdef in one place.

It is a chicken-and-egg problem: until you do thing in a more "standard" way, you won't be able to attract other devs... You may not like automake/autoconf/pkgconfig, for example, but they are what many are familiar. If you make "starting to look" at laidout too hard and finding one's way around too difficult, many won't bother :-).

There is another thing about the freetype issue - if my impression serves, the file which was affected wasn't in the directory where the sub-make target was happening (you were doing something along the line of "in one directory, compile here stuff + ../elsewhere/source.cc" ). That's confusing for even experienced devs. You might consider using ranlib more often for that sort of cross-directory compilation.

**Comment by HinTak** [comment]
I keep forgetting the "make depends" step. That's also unusual for many software. One thing you might try is to make the default target depends on one of the auto-generated depends files - so that 'make depends' is automagically run if a particular file is missing. That would at least bring the experience of woring on laidout more familiar superficiallay to some people - I.e. "./autogen.sh.sh && ./configure && make" works straight from git repo, more in line with how one habitually does with other software.

**Comment by tomlechner** [comment]
The freetype thing, I'm not sure what you mean. Compiling should only happen in the directory of the file. Maybe there was a header file from another directory pulled in that messed up something? If it is calling targets in parent directories, then somethings wrong.

Well, releases have makedepend files already there. I know I'm extremely biased, but to me, having one extra line "make depends" is no different than have one extra line "./autogen". I don't commit the makedepend files because unfortunately imake's makedepend writes out absolute dependency paths, not relative paths. Ideally, I'd have a script that does what makedepend does, but outputs relative paths. Then I could remove the dependency on xutils-dev/imake, and also commit the makedepend files, which would also remove the need for the extra "make depends" step.

**Comment by HinTak** [comment]
If I remember correctly, the file which needed freetype includes is not in the directory where the make target that failed, but in another sub-directory of the parent directory where the failed make target is.

My comment regarding 'make depends' is not about number of extra lines of commands, but about making the 'starting experience' more similar to other experienced dev's who habitually do "./autogen.sh && ./configure && make" from a source checkout. It is about making laidout "less surprising": people do not want to read long README's if they can get away with not reading it, just using their habits gained from building other software. i.e. they see there is a autogen.sh, they assume it will (superficially) build like others, and just not reading the README.
